
services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-container
    networks:
      - react-network

  nginx:
    image: nginx:alpine
    container_name: nginx-react
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./react-app/build:/usr/share/nginx/html
    ports:
      - "8085:80"
    depends_on:
      - react-app
    networks:
      - react-network

networks:
  react-network:
