
services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    restart: always

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-container
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    restart: always
