
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress-container
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    ports:
      - "8088:80"
    restart: always
    networks:
      - wordpress-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql-container-bai6

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - wordpress-network
    restart: always

networks:
  wordpress-network:
