
services:
  mysql:
    image: mysql:latest
    container_name: mysql-containerVolume
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3333:3306"
    restart: always

volumes:
  mysql-data:
